### ISSUE TITLE
Update PlayFramework version in play-acl to 2.6

### ISSUE THREAD

**Issue by Kitefusion** [de-ceow/scala-acl#3]
Because PlayFramework 2.6 was released in June 23 it would be nice to update the version in the play-acl project.
At the same time it is possible to add the same scala versions to the play-acl project as in the scala-acl because PlayFramework 2.6 is also compiled agaings scala 2.12

Here is the corresponsing Pull-Request: #2

**Comment by Scyks** [comment]
@Kitefusion Thank you for contributing and updating the play component to 2.6. I already merged the PR and triggered the release process. It should be available soon.
